name: Geert-Jan GitHub Actions Demo

on:
  push:
    branches:
      - main   # only run when pushing to 'main'

jobs:
  create-mavne-package-skip-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        cache-dependency-path: 'sub-project/pom.xml' # optional
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml